# Generated by Django 5.2.14 on 2026-05-13 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEUI', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(blank=True, default='Unknown Device', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCnt', models.IntegerField()),
                ('data_raw', models.CharField(max_length=255)),
                ('data_hex', models.CharField(blank=True, max_length=255)),
                ('is_passing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='hmapp.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'fCnt'), name='unique_fcnt_per_device')],
            },
        ),
    ]
